import { api } from '../services/api.js';
import { renderSidebar } from '../components/Sidebar.js';
import { showModal } from '../components/Modal.js';
import { showToast } from '../components/Toast.js';

export async function renderReportsView() {
  const reports = await api.getReports();

  const container = document.createElement('div');
  container.className = 'flex-1 flex w-full min-h-[calc(100vh-4rem)]';

  const renderContent = () => {
    return `
      ${renderSidebar('/reports')}

      <div class="flex-1 p-4 sm:p-6 lg:p-8 space-y-6 overflow-y-auto max-w-7xl">
        
        <!-- Header -->
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border pb-4">
          <div>
            <h1 class="text-xl sm:text-2xl font-bold text-content-primary tracking-tight">Meteorological Reports & Compliance Exports</h1>
            <p class="text-xs text-content-secondary mt-0.5">Automated telemetry audits, sensor calibration certificates, and anomaly incident logs.</p>
          </div>

          <button id="btn-create-report" class="btn-primary text-xs px-3.5 py-2 flex items-center space-x-1.5 self-start sm:self-auto">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>
            <span>Generate New Audit Report</span>
          </button>
        </div>

        <!-- Reports List -->
        <div class="space-y-4">
          ${reports.map(rep => {
            let parsedSummary = {};
            try {
              parsedSummary = typeof rep.summaryJson === 'string' ? JSON.parse(rep.summaryJson) : (rep.summaryJson || {});
            } catch (e) {
              parsedSummary = {};
            }

            return `
              <div class="atmospheric-card p-5 sm:p-6 space-y-4">
                <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div class="flex items-center space-x-3">
                    <span class="px-2 py-0.5 rounded bg-subtle border border-border text-content-secondary font-mono text-[10px] font-medium">${rep.reportType}</span>
                    <h3 class="text-base font-bold text-content-primary">${rep.title}</h3>
                  </div>

                  <div class="flex items-center space-x-3 font-mono text-xs">
                    <span class="text-content-muted">Generated by: <strong class="text-content-secondary font-medium">${rep.generatedBy}</strong></span>
                    <span class="status-online">${rep.status}</span>
                  </div>
                </div>

                <div class="p-3.5 rounded-lg bg-subtle border border-border font-mono text-xs text-content-secondary grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <div>
                    <span class="text-[10px] text-content-muted uppercase block">DATE RANGE START</span>
                    <span class="text-content-primary font-medium tabular-nums">${new Date(rep.dateRangeStart).toLocaleDateString()}</span>
                  </div>
                  <div>
                    <span class="text-[10px] text-content-muted uppercase block">DATE RANGE END</span>
                    <span class="text-content-primary font-medium tabular-nums">${new Date(rep.dateRangeEnd).toLocaleDateString()}</span>
                  </div>
                  <div>
                    <span class="text-[10px] text-content-muted uppercase block">FORMAT</span>
                    <span class="text-content-primary font-semibold">${rep.fileFormat}</span>
                  </div>
                  <div>
                    <span class="text-[10px] text-content-muted uppercase block">TIMESTAMP</span>
                    <span class="text-content-muted tabular-nums">${new Date(rep.createdAt).toLocaleTimeString()}</span>
                  </div>
                </div>

                ${parsedSummary.recommendations ? `
                  <p class="text-xs text-content-secondary"><strong class="text-content-primary font-mono">RECOMMENDATIONS:</strong> ${parsedSummary.recommendations}</p>
                ` : ''}

                <!-- Download Real Export Button -->
                <div class="pt-2 flex justify-end border-t border-border">
                  <button class="download-report-btn btn-secondary text-xs px-4 py-1.5 flex items-center space-x-2" data-id="${rep.id}" data-title="${rep.title}">
                    <svg class="w-3.5 h-3.5 text-content-secondary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                    <span>Download Official ${rep.fileFormat} Export</span>
                  </button>
                </div>
              </div>
            `;
          }).join('')}
        </div>

      </div>
    `;
  };

  const updateView = () => {
    container.innerHTML = renderContent();

    // Trigger create modal
    const createBtn = container.querySelector('#btn-create-report');
    if (createBtn) {
      createBtn.onclick = () => {
        showModal({
          title: 'Generate Telemetry & Quality Audit Report',
          content: `
            <div class="space-y-3">
              <div>
                <label class="block text-content-secondary font-mono text-xs mb-1">REPORT TITLE</label>
                <input id="modal-rep-title" type="text" class="form-input text-xs" value="Monthly Network Health & Telemetry Verification Report" />
              </div>
              <div>
                <label class="block text-content-secondary font-mono text-xs mb-1">REPORT TYPE</label>
                <select id="modal-rep-type" class="form-input text-xs">
                  <option value="NETWORK_HEALTH">Network Health & Quality Audit</option>
                  <option value="ANOMALY_AUDIT">Incident & Anomaly Audit Log</option>
                  <option value="SENSOR_CALIBRATION">Sensor Transducer Calibration Record</option>
                  <option value="METEOROLOGICAL_TREND">Diurnal Climate Trend Summary</option>
                </select>
              </div>
              <div>
                <label class="block text-content-secondary font-mono text-xs mb-1">EXPORT FORMAT</label>
                <select id="modal-rep-format" class="form-input text-xs font-mono">
                  <option value="JSON">JSON (Machine-readable dataset)</option>
                  <option value="CSV">CSV (Tabular observations)</option>
                </select>
              </div>
            </div>
          `,
          confirmText: 'Generate Report',
          onConfirm: async () => {
            const title = document.getElementById('modal-rep-title').value;
            const reportType = document.getElementById('modal-rep-type').value;
            const fileFormat = document.getElementById('modal-rep-format').value;

            await api.generateReport({ title, reportType, fileFormat });
            showToast('Report generated successfully', 'success');
            updateView();
          }
        });
      };
    }

    // Attach real download action
    container.querySelectorAll('.download-report-btn').forEach(btn => {
      btn.onclick = () => {
        const id = btn.dataset.id;
        const title = btn.dataset.title || 'Report';
        const rep = reports.find(r => r.id === Number(id));

        const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(rep ? rep.summaryJson || JSON.stringify(rep, null, 2) : "{}");
        const downloadAnchor = document.createElement('a');
        downloadAnchor.setAttribute("href", dataStr);
        downloadAnchor.setAttribute("download", `SkyGuardAI_Report_${id}_${title.replace(/\s+/g, '_')}.json`);
        document.body.appendChild(downloadAnchor);
        downloadAnchor.click();
        downloadAnchor.remove();
        showToast(`Exported ${title}`, 'success');
      };
    });
  };

  updateView();
  return container;
}

